---
- hosts: UBUNTULoadbalancer
  vars_files:
  - vars/loadbalancervariables
  roles:
  - load-balancer

- hosts: UBUNTUKControlplane
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - controlplane

- hosts: UBUNTUKMaster
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - master

- hosts: UBUNTUKWorker
  vars_files:
  - vars/workervariables
  roles:
  - base
  - worker
