---
- hosts: UBUNTUKControlplane
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base

- hosts: UBUNTUKMaster
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base

  
- hosts: UBUNTUKWorker
  become: yes
  become_user: root
  vars_files:
  - vars/workervariables
  roles:
  - base

