---
- hosts: UBUNTUKControlplane
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - controlplane

- hosts: UBUNTUKMaster
  become: yes
  become_user: root
  vars_files:
  - vars/mastervariables
  roles:
  - base
  - master 
  
- hosts: UBUNTUKWorker
  become: yes
  become_user: root
  vars_files:
  - vars/workervariables
  roles:
  - base
  - worker
