- name: Initializing Kubernetes cluster
  shell: kubeadm init --pod-network-cidr={{cidr_v}} --control-plane-endpoint="192.168.2.8:6443" --apiserver-cert-extra-sans=192.168.2.8 --upload-certs
  register: output

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest={{ token_file }}

- name: Copying required files to root
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    
- name: Install Calico CNI
  shell: curl https://projectcalico.docs.tigera.io/manifests/calico.yaml -O

- name: Install Calico custom reesources
  shell: kubectl apply -f calico.yaml
    

