- name: Initializing Kubernetes cluster
  shell: kubeadm init --pod-network-cidr={{cidr_v}} --control-plane-endpoint="192.168.1.8:6443" --apiserver-cert-extra-sans=192.168.1.8 --upload-certs
  register: output

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest={{ token_file }}

- name: Copying required files to root
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
    
- name: Install Calico CNI
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml

- name: Install Calico custom reesources
  shell: kubectl create -f https://gist.githubusercontent.com/grzegorzgniadek/8f1ab792e2d1584d113602385ec38126/raw/26bbe10d338c3bba1325a58045f4d1df5094cd18/caliconetworkha.yaml
    

