- name: Upgrade all packages
  apt:
    upgrade: full

- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: Iptables Allow TCP
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: tcp
  with_items: "{{ ports_tcp }}"

- name: Iptables Allow UDP
  iptables:
    chain: INPUT
    destination_port: "{{ item }}"
    jump: ACCEPT
    protocol: udp
  with_items: "{{ ports_udp }}"

- name: Iptables ESTABLISHED,RELATED
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Firewall rule - drop any traffic without rule
  iptables:
    chain: INPUT
    policy: DROP

- name: Install dependencies
  apt: 
    name: "{{ item }}"
  with_items:
      - haproxy
      - curl

- name: Save iptables
  shell: iptables-save > /etc/iptables/rules.v4

- name: Insert config lines in haproxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      frontend kubernetes-frontend
          bind 192.168.1.8:6443
          mode tcp
          option tcplog
          default_backend kubernetes-backend

      backend kubernetes-backend
          mode tcp
          option tcp-check
          balance roundrobin
          server ubuntumaster1 192.168.1.2:6443 check fall 3 rise 2
          server ubuntumaster2 192.168.1.3:6443 check fall 3 rise 2
          server ubuntumaster3 192.168.1.4:6443 check fall 3 rise 2

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted