- name: Upgrade all packages
  apt:
    upgrade: full

- name: Disabling Swap on all nodes
  shell: swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '(^/.*swap*)'
    replace: '# \1'

- name: Install dependencies
  apt: 
    name: "{{ item }}"
  with_items:
      - haproxy
      - curl

- name: Insert config lines in haproxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    block: |
      frontend kubernetes-frontend
          bind 192.168.2.8:6443
          mode tcp
          option tcplog
          default_backend kubernetes-backend

      backend kubernetes-backend
          mode tcp
          option tcp-check
          balance roundrobin
          server ubuntumaster1 192.168.2.2:6443 check fall 3 rise 2
          server ubuntumaster2 192.168.2.3:6443 check fall 3 rise 2
          server ubuntumaster3 192.168.2.4:6443 check fall 3 rise 2

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted
